name: CI/CD

on:
  push:
    branches: [main]

jobs:
  ci_cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Use Node.js 16
        uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Lint code
        run: npm run ci:lint

      - name: Typecheck
        run: npm run ci:tsc

      - name: Tests
        run: npm run ci:test

      - name: Trigger render deploy via webhook
        uses: zzzze/webhook-trigger@d83e16935dfe5c1362f730e4326a59519d77ae5b
        with:
          data: '{"event_type":"build"}'
          webhook_url: ${{ secrets.WEBHOOK_URL }}
